### ISSUE TITLE
Can't add multiple files to a .SSD in one go [MMBExplorer]

### ISSUE THREAD

**Issue by lurkio** [robcfg/retrotools#1]
One slight problem with MMBExplorer on macOS Mojave is that I couldn't add more than one file to a .SSD at a time. Is there any way to increase that limit? The macOS file-selection dialog box would only let me select one file at a time.

**Comment by robcfg** [comment]
I just added the support and I can insert a number of disk images from the file browser.

It would be nice if you could compile and test it. Otherwise, I'll make a new release soon.

**Comment by lurkio** [comment]
Just built 6bd4cd0. Adding multiple files in one go **_doesn't_** seem to work. I tried to add two files (test1 and test2) to a .SSD, but it only added test1.

**Comment by lurkio** [comment]
I've only done a quick test, but adding multiple files at a time seems to work now.
