### ISSUE TITLE
MMBExplorer: directory name is missing from .inf when extracting file from .SSD

### ISSUE THREAD

**Issue by lurkio** [robcfg/retrotools#5]
In MMBExplorer I created a new .MMB file with just one .SSD slot. I then inserted a .SSD into that slot. The .SSD had a file called _O.TERP_ on it. 

When I extracted the file O.TERP to the desktop, two files were created on the desktop: TERP and TERP.inf. The latter, when viewed in a text editor, was shown to contain the filename (_TERP_) but **_without_** the DFS directory name (_O_). 

Instead, TERP.inf should have stored the filename as _O.TERP_

**Comment by robcfg** [comment]
Hi Lurkio!

I just checked it and it indeed happens as you say.

What would be the desired fix? To export the file as TERP with TERP.inf having the name as O.TERP, or to export the file as O.TERP and O.TERP.inf?

Thank you for your report!

**Comment by lurkio** [comment]
I would prefer it to export the file as O.TERP and O.TERP.inf. That would be consistent with DFSExplorer (if I remember the name of that app correctly) and perhaps with other tools too. Plus, I think you really do have to do that if you're exporting two files with the same name but different directories (assuming that exporting multiple files at once is possible in MMBExplorer -- I can't remember off the top of my head)..!

**Comment by robcfg** [comment]
Hi,

I have it working, but in case the inf file is missing, names can go very wrong due to the BBC<->Host character translation.

For example, if you have a $.myfile file with its inf file, it will get inserted as $.myfile, but if the inf file is missing, it will get inserted as $.</myfil

Is that the intended way of working?

**Comment by lurkio** [comment]
No. I would expect the file $.myfile to be added to a .SSD as $.myfile in all circumstances.

**Comment by robcfg** [comment]
I just made a new release because I think it's working properly now.

Would you mind giving it a try?

Thanks a lot!

**Comment by lurkio** [comment]
Yes, it seems to be working now -- sort of...

Something I just noticed is that when I used MMBExplorer to export a BASIC program file from a .SSD to my Mac desktop, the load and exec addresses in the accompanying .inf file were _31900_ and _38023_, which are wrong. They should be _FF1900_ and _FF8023_. 

Somehow, though, when I used DFSImager to put the exported file from the Mac desktop back onto a blank .SSD and then loaded the .SSD in BeebEm, the load and exec addresses were magically corrected to _FF1900_ and _FF8023_ (even though DFSImager briefly got confused and displayed the wrong addresses in its app window until I closed and reopened the .SSD, whereupon the addresses had magically transformed into the correct values!)!.

I'm not sure what's going on, but I've tried manually editing the .inf so that the load and exec addresses are the correct values _FF1900_ and _FF8023_, and it hasn't caused any problems so far, so I'd suggest that MMBExplorer should be updated so that it will output the correct load and exec addresses into the .inf file when it exports a file from a .SSD.

**Comment by lurkio** [comment]
See also the recently updated behaviour of Disc Image Manager:

https://stardot.org.uk/forums/viewtopic.php?p=316103#p316103
