### ISSUE TITLE
MMBExplorer: extracted files have wrong load- and exec-addresses

### ISSUE THREAD

**Issue by lurkio** [robcfg/retrotools#6]
When I used MMBExplorer to export a BASIC program file from a .SSD to my Mac desktop, the load and exec addresses in the accompanying .inf file were _31900_ and _38023_, which are wrong. They should be _FF1900_ and _FF8023_. 

However, if I use _DFSImager_ to do the same thing, the .inf file written by DFSImager contains the _correct_ values. Here are the full contents of the .inf file written by DFSImager:

`$.PROG    FF1900 FF8023 CRC= C52` 

I've tried manually editing the .inf file created by MMBExplorer and correcting the load and exec addresses to _FF1900_ and _FF8023_, and it hasn't caused any problems so far. 

Therefore I would suggest that MMBExplorer should be updated so that it will write the correct load and exec addresses into the .inf file when it exports a file from a .SSD to the host OS — just as DFSImager already does.

Btw, the following discussion on Stardot may or may not be helpful!:

[https://stardot.org.uk/forums/viewtopic.php?p=316109#p316109](https://stardot.org.uk/forums/viewtopic.php?p=316109#p316109)

**Comment by robcfg** [comment]
Thanks for opening a new issue! :D

When I read the documentation, it only mentioned the two bits over 0xFFFF which would mean an address on a secondary processor, but it didn't specify whether the remaining bit would need to be 0 or 1, leading to this issue.

I'm perfectly fine by filling the missing bits with 1 instead of 0, but I think it would be nice to confirm why that is the case.

**Comment by robcfg** [comment]
I found some interesting bit of info here: http://beebwiki.mdfs.net/Acorn_DFS_disc_format#Acorn_System_DFS

> Note on load and execution addresses: If bits 16 and 17 of the address are both set, the address refers to I/O processor memory and OSFILE will return the address ORed with &FFFF0000 in its parameter block. Otherwise it is an address in second processor memory and OSFILE will return the address as is. In practice the bits are sometimes found clear when they should be set.

On the same document, addresses are shown the same way I do, as they are stored on disk as 18-bit addresses, not 24 or 32-bit ones. So, strictly speaking, the address I'm showing is correct, and the same as the ones in the 0xFFxxxx form, but the latter with the higher 6 bits set to 1 by the OS.

**Comment by robcfg** [comment]
Fixed issue. Files extracted with the old addresses will show with the new ones and upon exported, the inf files will also have the new addresses.
