### ISSUE TITLE
MMBExplorer make fails

### ISSUE THREAD

**Issue by bteamfox** [robcfg/retrotools#7]
I am run Manjaro Linux XFCE 21.1.4 and have installed Cmake and FLTK(from AUR). All packages are upto date.
 I CD to the build folder then type:
"cmake -DCMAKE_BUILD_TYPE=Release .." as you can see below.
Then type "make", but make fails. Any ideas what is going wrong and how to fix it as it does the same thing on my Laptop with the same version of Manjaro. Im new to Linux and Github so I hope you can help.

[ian@ian-ms7b78 mmbexplorer]$ cd build/
[ian@ian-ms7b78 build]$ ls
readme.txt
[ian@ian-ms7b78 build]$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at /usr/share/cmake-3.21/Modules/FindOpenGL.cmake:315 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  /usr/share/cmake-3.21/Modules/FindFLTK.cmake:87 (find_package)
  CMakeLists.txt:12 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/libOpenGL.so   
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ian/retrotools/mmbexplorer/build
[ian@ian-ms7b78 build]$ make
[  0%] Built target getscmversion
[ 14%] Building CXX object CMakeFiles/MMBExplorer.dir/src/MMBExplorer.cpp.o
[ 28%] Building CXX object CMakeFiles/MMBExplorer.dir/src/MMBFile.cpp.o
[ 42%] Building CXX object CMakeFiles/MMBExplorer.dir/src/MMBE_Commands.cpp.o
[ 57%] Building CXX object CMakeFiles/MMBExplorer.dir/src/MMBE_Gui.cpp.o
[ 71%] Building CXX object CMakeFiles/MMBExplorer.dir/src/MMBE_Callbacks.cpp.o
[ 85%] Building CXX object CMakeFiles/MMBExplorer.dir/src/AcornDFS.cpp.o
[100%] Linking CXX executable MMBExplorer
/usr/bin/ld: /usr/lib/libfltk.a(Fl_X11_Window_Driver.cxx.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/MMBExplorer.dir/build.make:196: MMBExplorer] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/MMBExplorer.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
[ian@ian-ms7b78 build]$

**Comment by robcfg** [comment]
I'm glad you managed to get it working!

I made a silly mistake on the above instructions, which is that I forgot to add ¨..¨ at the end of the cmake line
`cmake -DCMAKE_BUILD_TYPE=Release ..`

The build folder is for executing that command so all build related files are kept separated. Thus the need to tell cmake that the CMakeLists.txt file is in the previous folder (..)

Cheers,
Rob
